feat: create roaster endpoint, add node api port env var, and express…
milharal-dev/detona-dev pull request #15
Opened 2024-08-13 14:55 UTC by VINNE7

… json middleware into index.ts

2024-08-13 16:49 UTC, mattpsvreis requested changes, later dismissed

2024-08-13 16:49 UTC, mattpsvreis commented on backend/package.json
> +    "start": "npm run build &&node dist/index.js"
Use yarn ao invés de npm.

Npm é horrível de todas as opções.

2024-08-13 16:49 UTC, mattpsvreis commented on backend/src/index.ts
> +await main().catch(console.error);
A função main() em contexto Express precisar ser async? Meio estranho esse await async.

2024-08-13 17:04 UTC, VINNE7 commented on backend/src/index.ts
> +await main().catch(console.error);
Preciso remover essa linha, eu coloquei porque estava testando algo. Essa função main nem precisa ser async, creio que ela estava como async antes por conta do await do getAllRepoReadmes.

2024-08-13 17:11 UTC, mattpsvreis commented on backend/package.json
> +    "start": "npm run build &&node dist/index.js"
Troca o `npm run build` por `tsc` mesmo.

2024-08-14 00:47 UTC, rdenadai approved these changes
Algumas sugestoes de melhorias ...

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +      username: req.body.username,
Suggestion:
Algum fallback caso o nome de usuario venha vazio

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +      per_page: 5,
Suggestion:
Adicionar como um constante ou envvar no projeto ...

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +  const repoNames = repos.map((repo) => repo.name);
Suggestion:
Seria bom checar se foram retornados repositorios antes de realizar qualquer operacao...

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +  const repoReadmes = await getAllReadmes(repoNames, req.body.username).then(
Suggestion:
Acho que pode criar uma var no comeco para conter o username.

```javascript
const username = req?.body?.username;
```

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +    model: "gpt-4o-mini",
Suggestion:
Adicionar `model` e `temperature` como constantes ou envvars ao projeto.

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +          req.body.username
Suggestion:
Como comentei colocar em uma var la no comeco

2024-08-14 00:47 UTC, rdenadai commented on backend/src/routes/roaster.routes.ts
> +    content: openApiResponse.choices[0].message.content,
```suggestion
    content: openApiResponse?.choices?.[0]?.message?.content ?? "Nenhum conteudo encontrado para fazer um roast!",
```

2024-10-19 13:42 UTC, rdenadai commented
@VINNE7 como estamos aqui ?

2025-11-27 15:49 UTC, thelinuxlich approved these changes

2025-11-29 22:34 UTC, ryukinix approved these changes

2025-11-29 22:39 UTC, merged

2025-11-30 00:18 UTC, mattpsvreis commented
KKKKKKKKKKKKKK o que aconteceu que reviveram isso aq @ryukinix

2025-11-30 00:19 UTC, ryukinix commented
Não faço ideia, o @thelinuxlich aprovou e decidi fazer merge kk